/**
 * Copart + IAAI pickup/branch locations, merged and deduplicated, compiled
 * from published branch-location listings (not a live feed). Branches open,
 * close, and get renamed over time, so treat this as a strong representative
 * list covering all 50 states rather than a guaranteed-current inventory —
 * verify an exact branch with us before relying on it for logistics.
 */
export const PICKUP_LOCATIONS: string[] = [
  "Tanner, AL",
  "Birmingham, AL",
  "Montgomery, AL",
  "Mobile, AL",
  "Dothan, AL",
  "Anchorage, AK",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Little Rock, AR",
  "Fayetteville, AR",
  "Vallejo, CA",
  "Sacramento, CA",
  "South Sacramento, CA",
  "Hayward, CA",
  "Fresno, CA",
  "Bakersfield, CA",
  "San Jose, CA",
  "San Bernardino, CA",
  "Los Angeles, CA",
  "Van Nuys, CA",
  "San Diego, CA",
  "Martinez, CA",
  "Rancho Cucamonga, CA",
  "Sun Valley, CA",
  "Anaheim, CA",
  "Carson, CA",
  "Perris, CA",
  "East Bay, CA",
  "Denver, CO",
  "Denver South, CO",
  "Denver East, CO",
  "Colorado Springs, CO",
  "Hartford, CT",
  "Seaford, DE",
  "Washington, DC",
  "Miami North, FL",
  "Miami Central, FL",
  "Miami South, FL",
  "Tampa South, FL",
  "Jacksonville West, FL",
  "Jacksonville East, FL",
  "Orlando, FL",
  "Orlando North, FL",
  "West Palm Beach, FL",
  "Fort Pierce, FL",
  "Ocala, FL",
  "Tallahassee, FL",
  "Punta Gorda, FL",
  "Clearwater, FL",
  "Atlanta, GA",
  "Atlanta West, GA",
  "Atlanta East, GA",
  "Atlanta South, GA",
  "Atlanta North, GA",
  "Savannah, GA",
  "Tifton, GA",
  "Cartersville, GA",
  "Honolulu, HI",
  "Boise, ID",
  "Chicago North, IL",
  "Chicago South, IL",
  "Chicago West, IL",
  "Peoria, IL",
  "Wheeling, IL",
  "Indianapolis, IN",
  "Fort Wayne, IN",
  "Hammond, IN",
  "Des Moines, IA",
  "Davenport, IA",
  "Kansas City, KS",
  "Wichita, KS",
  "Lexington West, KY",
  "Lexington East, KY",
  "Walton, KY",
  "Louisville, KY",
  "Ashland, KY",
  "Bowling Green, KY",
  "Baton Rouge, LA",
  "New Orleans, LA",
  "Shreveport, LA",
  "Lyman, ME",
  "Baltimore, MD",
  "Dundalk, MD",
  "Elkton, MD",
  "Boston South, MA",
  "Boston North, MA",
  "West Warren, MA",
  "Boston (Shirley), MA",
  "Detroit, MI",
  "Lansing, MI",
  "Kincheloe, MI",
  "Flint, MI",
  "Ionia, MI",
  "Minneapolis, MN",
  "Minneapolis North, MN",
  "Saint Cloud, MN",
  "Jackson, MS",
  "Saint Louis, MO",
  "Springfield, MO",
  "Columbia, MO",
  "Sikeston, MO",
  "Helena, MT",
  "Billings, MT",
  "Lincoln, NE",
  "Las Vegas, NV",
  "Reno, NV",
  "Candia, NH",
  "Glassboro, NJ",
  "Somerville, NJ",
  "Trenton, NJ",
  "Avenel, NJ",
  "Central New Jersey, NJ",
  "Albuquerque, NM",
  "Newburgh, NY",
  "Syracuse, NY",
  "Long Island, NY",
  "Rochester, NY",
  "Albany, NY",
  "Buffalo, NY",
  "China Grove, NC",
  "Raleigh, NC",
  "Mebane, NC",
  "Asheville, NC",
  "Charlotte, NC",
  "Concord, NC",
  "Columbus, OH",
  "Cleveland East, OH",
  "Cleveland West, OH",
  "Dayton, OH",
  "Akron-Canton, OH",
  "Cincinnati, OH",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Portland North, OR",
  "Portland South, OR",
  "Eugene, OR",
  "Philadelphia, PA",
  "Philadelphia East, PA",
  "Pittsburgh North, PA",
  "Pittsburgh South, PA",
  "Pittsburgh East, PA",
  "Harrisburg, PA",
  "York Haven, PA",
  "Chambersburg, PA",
  "Altoona, PA",
  "Scranton, PA",
  "Bridgeport, PA",
  "Columbia, SC",
  "Greer, SC",
  "Charleston, SC",
  "Memphis, TN",
  "Nashville, TN",
  "Knoxville, TN",
  "Chattanooga, TN",
  "Houston, TX",
  "Dallas, TX",
  "Dallas South, TX",
  "Dallas/Fort Worth, TX",
  "Fort Worth, TX",
  "Lufkin, TX",
  "Longview, TX",
  "El Paso, TX",
  "Austin, TX",
  "Austin North, TX",
  "McAllen, TX",
  "Abilene, TX",
  "San Antonio, TX",
  "Amarillo, TX",
  "Corpus Christi, TX",
  "Waco, TX",
  "Salt Lake City, UT",
  "Burlington, VT",
  "Danville, VA",
  "Hampton, VA",
  "Richmond, VA",
  "Culpeper, VA",
  "North Seattle, WA",
  "Graham, WA",
  "Pasco, WA",
  "Spokane, WA",
  "Charleston, WV",
  "Buckhannon, WV",
  "Madison, WI",
  "Milwaukee, WI",
  "Appleton, WI",
  "Casper, WY",
];
