/**
 * Real local-transportation rates: the cost to have a driver pick a vehicle
 * up from its Copart/IAAI auction lot and deliver it to the shipping yard
 * where it's loaded for ocean freight. Compiled from a 2026 rate sheet
 * covering Car and Motorcycle pickups; SUV uses the Car rate plus a flat
 * surcharge (see SUV_SURCHARGE_USD) since the source sheet rarely
 * distinguishes SUV pricing. Locations/vehicle-kinds not covered here (the
 * rest of the calculator's vehicle categories, or a network with no listed
 * rate for a given city) fall back to the flat default the caller supplies.
 *
 * Where the source sheet listed conflicting duplicate rows for the same
 * city/network/vehicle, the lower of the two values was kept.
 */
export type AuctionNetwork = "copart" | "iaai";

type RateEntry = { car?: number; motorcycle?: number };

const LOCAL_TRANSPORT_RATES: Record<string, Partial<Record<AuctionNetwork, RateEntry>>> = {
  "Abilene, TX": { iaai: { car: 400, motorcycle: 350 } },
  "Adelanto, CA": { copart: { car: 300 } },
  "Akron-Canton, OH": { iaai: { car: 450, motorcycle: 400 } },
  "Albany, NY": { copart: { car: 325, motorcycle: 300 }, iaai: { car: 300, motorcycle: 245 } },
  "Albuquerque, NM": { copart: { car: 540 }, iaai: { car: 540, motorcycle: 420 } },
  "Altoona, PA": { iaai: { car: 450, motorcycle: 325 } },
  "Amarillo, TX": { copart: { car: 470 }, iaai: { car: 470, motorcycle: 420 } },
  "Anaheim, CA": { iaai: { car: 180, motorcycle: 180 } },
  "Andrews, TX": { copart: { car: 450 } },
  "Antelope, CA": { copart: { car: 400, motorcycle: 300 } },
  "Appleton, WI": { iaai: { car: 270, motorcycle: 260 } },
  "Asheville, NC": { iaai: { car: 350, motorcycle: 250 } },
  "Ashland, KY": { iaai: { car: 550, motorcycle: 400 } },
  "Atlanta East, GA": { copart: { car: 320, motorcycle: 220 }, iaai: { car: 320, motorcycle: 220 } },
  "Atlanta North, GA": { copart: { car: 325, motorcycle: 275 }, iaai: { car: 320, motorcycle: 220 } },
  "Atlanta South, GA": { iaai: { car: 320, motorcycle: 220 } },
  "Atlanta West, GA": { copart: { car: 325, motorcycle: 225 } },
  "Atlanta, GA": { iaai: { car: 320, motorcycle: 220 } },
  "Augusta, GA": { copart: { car: 260, motorcycle: 200 } },
  "Austin North, TX": { copart: { car: 300, motorcycle: 250 } },
  "Austin, TX": { copart: { car: 300, motorcycle: 250 }, iaai: { car: 300, motorcycle: 250 } },
  "Avenel, NJ": { iaai: { car: 150, motorcycle: 100 } },
  "Bakersfield, CA": { copart: { car: 250, motorcycle: 220 } },
  "Baltimore East, MD": { copart: { car: 350, motorcycle: 300 } },
  "Baltimore, MD": { copart: { car: 350, motorcycle: 300 }, iaai: { car: 350, motorcycle: 300 } },
  "Bartlett, IL": { copart: { car: 150, motorcycle: 150 } },
  "Baton Rouge, LA": { iaai: { car: 300, motorcycle: 275 } },
  "Billings, MT": { copart: { car: 800, motorcycle: 800 }, iaai: { car: 800, motorcycle: 800 } },
  "Birmingham, AL": { iaai: { car: 400, motorcycle: 360 } },
  "Bismarck, ND": { copart: { car: 750, motorcycle: 725 } },
  "Boise, ID": { iaai: { car: 450, motorcycle: 425 } },
  "Boston (Shirley), MA": { iaai: { car: 375, motorcycle: 250 } },
  "Boston North, MA": { copart: { car: 375, motorcycle: 320 } },
  "Boston South, MA": { copart: { car: 350, motorcycle: 320 } },
  "Bowling Green, KY": { iaai: { car: 400, motorcycle: 325 } },
  "Bridgeport, PA": { iaai: { car: 200, motorcycle: 150 } },
  "Buckhannon, WV": { iaai: { car: 550, motorcycle: 500 } },
  "Buffalo, NY": { iaai: { car: 500, motorcycle: 420 } },
  "Burlington, VT": { iaai: { car: 480, motorcycle: 400 } },
  "Candia, NH": { copart: { car: 425, motorcycle: 375 } },
  "Carson, CA": { iaai: { car: 200, motorcycle: 200 } },
  "Cartersville, GA": { copart: { car: 325, motorcycle: 300 } },
  "Casper, WY": { iaai: { car: 950, motorcycle: 925 } },
  "Central New Jersey, NJ": { iaai: { car: 200, motorcycle: 150 } },
  "Chambersburg, PA": { copart: { car: 350, motorcycle: 320 } },
  "Charleston, SC": { iaai: { car: 250, motorcycle: 200 } },
  "Charleston, WV": { copart: { car: 570, motorcycle: 495 } },
  "Charlotte, NC": { iaai: { car: 350, motorcycle: 250 } },
  "Chattanooga, TN": { iaai: { car: 450, motorcycle: 350 } },
  "Chicago North, IL": { copart: { car: 220, motorcycle: 220 }, iaai: { car: 225, motorcycle: 225 } },
  "Chicago South, IL": { copart: { car: 200, motorcycle: 200 }, iaai: { car: 200, motorcycle: 175 } },
  "Chicago West, IL": { iaai: { motorcycle: 175 } },
  "China Grove, NC": { copart: { car: 275, motorcycle: 270 } },
  "Cincinnati South, OH": { iaai: { car: 450, motorcycle: 380 } },
  "Cincinnati, OH": { iaai: { car: 450, motorcycle: 380 } },
  "Clearwater, FL": { iaai: { car: 375, motorcycle: 260 } },
  "Cleveland East, OH": { copart: { car: 425, motorcycle: 400 }, iaai: { car: 500, motorcycle: 400 } },
  "Cleveland West, OH": { copart: { car: 500, motorcycle: 300 } },
  "Colorado Springs, CO": { copart: { car: 625, motorcycle: 475 }, iaai: { car: 625, motorcycle: 475 } },
  "Colton, CA": { iaai: { car: 300 } },
  "Columbia, MO": { copart: { car: 400, motorcycle: 320 } },
  "Columbia, SC": { copart: { car: 250, motorcycle: 245 }, iaai: { car: 275, motorcycle: 200 } },
  "Columbus, OH": { copart: { car: 650, motorcycle: 600 }, iaai: { car: 600, motorcycle: 550 } },
  "Concord, NC": { iaai: { car: 350, motorcycle: 250 } },
  "Corpus Christi, TX": { copart: { car: 270, motorcycle: 270 }, iaai: { car: 295, motorcycle: 225 } },
  "CrashedToys East Bethel, MN": { copart: { car: 400, motorcycle: 350 } },
  "CrashedToys Eldridge, IA": { copart: { car: 300, motorcycle: 270 } },
  "CrashedToys Minneapolis, MN": { copart: { car: 350, motorcycle: 350 } },
  "CrashedToys Sacramento, CA": { copart: { car: 375, motorcycle: 350 } },
  "Culpeper, VA": { iaai: { car: 400, motorcycle: 300 } },
  "Dallas South, TX": { copart: { car: 275 } },
  "Dallas, TX": { copart: { car: 300, motorcycle: 300 }, iaai: { car: 275, motorcycle: 225 } },
  "Dallas/Fort Worth, TX": { iaai: { car: 275, motorcycle: 225 } },
  "Danville, VA": { copart: { car: 430, motorcycle: 340 } },
  "Davenport, IA": { copart: { car: 300, motorcycle: 270 }, iaai: { car: 325, motorcycle: 270 } },
  "Dayton, OH": { copart: { car: 400, motorcycle: 300 }, iaai: { car: 450, motorcycle: 400 } },
  "Denver Central, CO": { copart: { car: 700 } },
  "Denver East, CO": { iaai: { car: 700, motorcycle: 600 } },
  "Denver South, CO": { copart: { car: 700, motorcycle: 600 } },
  "Denver, CO": { copart: { car: 700, motorcycle: 600 }, iaai: { car: 700, motorcycle: 600 } },
  "Des Moines, IA": { copart: { car: 325, motorcycle: 300 }, iaai: { car: 400, motorcycle: 300 } },
  "Detroit, MI": { copart: { car: 400, motorcycle: 350 }, iaai: { car: 475, motorcycle: 380 } },
  "Dothan, AL": { iaai: { car: 375, motorcycle: 300 } },
  "Dundalk, MD": { iaai: { car: 300, motorcycle: 250 } },
  "Dyer, IN": { copart: { car: 225, motorcycle: 175 } },
  "Earlington, KY": { copart: { car: 500, motorcycle: 440 } },
  "East Bay, CA": { iaai: { car: 400, motorcycle: 300 } },
  "El Paso, TX": { copart: { car: 425, motorcycle: 395 }, iaai: { car: 500, motorcycle: 400 } },
  "Elkton, MD": { iaai: { car: 350, motorcycle: 300 } },
  "Englishtown, NJ": { iaai: { car: 185, motorcycle: 135 } },
  "Erie, PA": { iaai: { car: 500, motorcycle: 425 } },
  "Eugene, OR": { copart: { car: 475, motorcycle: 325 }, iaai: { car: 350, motorcycle: 250 } },
  "Exeter, RI": { copart: { car: 350, motorcycle: 300 } },
  "Fargo, ND": { iaai: { car: 650, motorcycle: 525 } },
  "Fayetteville, AR": { copart: { car: 450, motorcycle: 425 }, iaai: { car: 500, motorcycle: 400 } },
  "Flint, MI": { copart: { car: 500, motorcycle: 450 }, iaai: { car: 500, motorcycle: 400 } },
  "Fontana, CA": { iaai: { car: 225, motorcycle: 225 } },
  "Fort Myers, FL": { iaai: { car: 375, motorcycle: 325 } },
  "Fort Pierce, FL": { copart: { car: 375, motorcycle: 300 }, iaai: { car: 375, motorcycle: 325 } },
  "Fort Wayne, IN": { copart: { car: 325, motorcycle: 325 } },
  "Fort Worth North, TX": { iaai: { car: 275, motorcycle: 200 } },
  "Fort Worth, TX": { copart: { car: 300, motorcycle: 250 } },
  "Fredericksburg South, VA": { iaai: { car: 400, motorcycle: 350 } },
  "Fredericksburg, VA": { copart: { car: 425, motorcycle: 400 } },
  "Freetown, MA": { copart: { car: 325, motorcycle: 300 } },
  "Fremont, CA": { iaai: { car: 375, motorcycle: 275 } },
  "Fresno, CA": { copart: { car: 350, motorcycle: 300 }, iaai: { car: 350, motorcycle: 275 } },
  "Glassboro East, NJ": { copart: { car: 250, motorcycle: 225 } },
  "Glassboro West, NJ": { copart: { car: 250, motorcycle: 200 } },
  "Graham, WA": { copart: { car: 175, motorcycle: 150 } },
  "Grand Rapids, MI": { iaai: { car: 400, motorcycle: 350 } },
  "Greensboro, NC": { iaai: { car: 325, motorcycle: 300 } },
  "Greenville, SC": { iaai: { car: 290, motorcycle: 275 } },
  "Greer, SC": { copart: { car: 260, motorcycle: 245 } },
  "Grenada, MS": { iaai: { car: 400 } },
  "Gulf Coast, MS": { iaai: { car: 475, motorcycle: 350 } },
  "Hammond, IN": { copart: { car: 160, motorcycle: 130 } },
  "Hampton, VA": { copart: { car: 420, motorcycle: 380 } },
  "Harrisburg, PA": { copart: { car: 275, motorcycle: 250 }, iaai: { car: 300, motorcycle: 275 } },
  "Hartford City, IN": { copart: { car: 275, motorcycle: 225 } },
  "Hartford South, CT": { copart: { car: 375, motorcycle: 300 }, iaai: { car: 225, motorcycle: 200 } },
  "Hartford Springfield, CT": { copart: { car: 300, motorcycle: 250 } },
  "Hartford, CT": { copart: { car: 300, motorcycle: 275 }, iaai: { car: 300, motorcycle: 250 } },
  "Hayward, CA": { copart: { car: 375, motorcycle: 345 } },
  "Helena, MT": { copart: { car: 650, motorcycle: 600 } },
  "High Desert, CA": { iaai: { car: 300, motorcycle: 250 } },
  "Houston East, TX": { copart: { car: 225 } },
  "Houston North, TX": { iaai: { car: 230, motorcycle: 200 } },
  "Houston South, TX": { iaai: { car: 230, motorcycle: 200 } },
  "Houston, TX": { copart: { car: 200, motorcycle: 200 }, iaai: { car: 225, motorcycle: 200 } },
  "Huntsville, AL": { iaai: { car: 375, motorcycle: 350 } },
  "IAA CAT Houston, TX": { iaai: { car: 200, motorcycle: 100 } },
  "Indianapolis South, IN": { iaai: { car: 300, motorcycle: 275 } },
  "Indianapolis, IN": { copart: { car: 275 }, iaai: { car: 275, motorcycle: 225 } },
  "Jackson, MS": { copart: { car: 350, motorcycle: 350 }, iaai: { car: 400, motorcycle: 350 } },
  "Jacksonville East, FL": { copart: { car: 200, motorcycle: 175 } },
  "Jacksonville North, FL": { copart: { car: 275, motorcycle: 225 } },
  "Jacksonville West, FL": { copart: { car: 200, motorcycle: 175 } },
  "Jacksonville, FL": { iaai: { car: 225, motorcycle: 200 } },
  "Kansas City East, MO": { iaai: { car: 375, motorcycle: 320 } },
  "Kansas City, KS": { copart: { car: 450, motorcycle: 400 }, iaai: { car: 400, motorcycle: 320 } },
  "Kincheloe, MI": { copart: { car: 725, motorcycle: 625 } },
  "Knoxville, TN": { copart: { car: 350, motorcycle: 320 }, iaai: { car: 440, motorcycle: 400 } },
  "Lafayette, LA": { iaai: { car: 350, motorcycle: 300 } },
  "Lansing, MI": { copart: { car: 400, motorcycle: 325 } },
  "Las Vegas, NV": { copart: { car: 360, motorcycle: 320 }, iaai: { car: 375, motorcycle: 295 } },
  "Laurel, MD": { iaai: { car: 300, motorcycle: 250 } },
  "Lexington East, KY": { copart: { motorcycle: 360 } },
  "Lexington West, KY": { copart: { car: 360 } },
  "Lexington, SC": { iaai: { car: 380, motorcycle: 320 } },
  "Lincoln, IL": { iaai: { car: 280, motorcycle: 230 } },
  "Lincoln, NE": { copart: { car: 390, motorcycle: 380 } },
  "Little Rock, AR": { copart: { car: 425, motorcycle: 420 }, iaai: { car: 430, motorcycle: 350 } },
  "Long Beach, CA": { copart: { car: 175, motorcycle: 175 } },
  "Long Island, NY": { copart: { car: 275, motorcycle: 250 }, iaai: { car: 300, motorcycle: 250 } },
  "Longview, TX": { copart: { car: 250, motorcycle: 240 }, iaai: { car: 250, motorcycle: 230 } },
  "Los Angeles South, CA": { iaai: { car: 200, motorcycle: 200 } },
  "Los Angeles, CA": { copart: { car: 175, motorcycle: 160 }, iaai: { car: 200, motorcycle: 200 } },
  "Louisville North, KY": { iaai: { car: 425, motorcycle: 320 } },
  "Louisville, KY": { copart: { car: 350, motorcycle: 295 }, iaai: { car: 425, motorcycle: 320 } },
  "Lubbock, TX": { iaai: { car: 450, motorcycle: 350 } },
  "Lufkin, TX": { copart: { car: 250, motorcycle: 240 } },
  "Lyman, ME": { copart: { car: 425, motorcycle: 425 } },
  "Macon, GA": { iaai: { car: 260, motorcycle: 200 } },
  "Madison South, WI": { copart: { car: 300, motorcycle: 275 } },
  "Madison, WI": { copart: { car: 265, motorcycle: 250 } },
  "Manchester, NH": { iaai: { car: 400, motorcycle: 300 } },
  "Martinez, CA": { copart: { car: 390, motorcycle: 365 } },
  "McAllen, TX": { copart: { car: 350, motorcycle: 350 }, iaai: { car: 350, motorcycle: 300 } },
  "Mebane, NC": { copart: { car: 300, motorcycle: 270 } },
  "Memphis, TN": { copart: { car: 450, motorcycle: 395 }, iaai: { car: 500, motorcycle: 400 } },
  "Mentone, CA": { copart: { car: 300, motorcycle: 300 } },
  "Metro DC, MD": { iaai: { car: 350, motorcycle: 300 } },
  "Miami Central, FL": { copart: { car: 350, motorcycle: 325 } },
  "Miami North, FL": { copart: { car: 350, motorcycle: 325 }, iaai: { car: 350, motorcycle: 325 } },
  "Miami South, FL": { copart: { car: 400, motorcycle: 350 } },
  "Miami, FL": { iaai: { car: 350, motorcycle: 325 } },
  "Milwaukee North, WI": { copart: { car: 225, motorcycle: 225 } },
  "Milwaukee South, WI": { copart: { car: 225, motorcycle: 225 } },
  "Milwaukee, WI": { iaai: { car: 225, motorcycle: 225 } },
  "Minneapolis North, MN": { copart: { car: 350, motorcycle: 350 } },
  "Minneapolis South, MN": { iaai: { car: 430, motorcycle: 350 } },
  "Minneapolis, MN": { copart: { car: 350, motorcycle: 350 } },
  "Minneapolis/St. Paul, MN": { iaai: { car: 430, motorcycle: 350 } },
  "Missoula, MT": { iaai: { car: 590, motorcycle: 550 } },
  "Mobile South, AL": { copart: { car: 420, motorcycle: 420 } },
  "Mobile, AL": { copart: { car: 425, motorcycle: 425 } },
  "Mocksville, NC": { copart: { car: 300, motorcycle: 245 } },
  "Montgomery, AL": { copart: { car: 350, motorcycle: 295 } },
  "Napa, CA": { copart: { car: 475, motorcycle: 400 } },
  "Nashville, TN": { copart: { car: 400, motorcycle: 350 }, iaai: { car: 380, motorcycle: 330 } },
  "New Castle, DE": { iaai: { car: 250, motorcycle: 225 } },
  "New Orleans East, LA": { iaai: { car: 450, motorcycle: 380 } },
  "New Orleans, LA": { copart: { car: 450, motorcycle: 400 }, iaai: { car: 450, motorcycle: 380 } },
  "Newburgh, NY": { copart: { car: 275, motorcycle: 275 }, iaai: { car: 275, motorcycle: 250 } },
  "North Charleston, SC": { copart: { car: 270, motorcycle: 220 } },
  "North Hollywood, CA": { iaai: { car: 200, motorcycle: 200 } },
  "North Seattle, WA": { copart: { car: 225, motorcycle: 200 } },
  "Northern New Jersey, NJ": { iaai: { car: 130, motorcycle: 130 } },
  "Northern Virginia, VA": { iaai: { car: 400, motorcycle: 350 } },
  "Ocala, FL": { copart: { car: 275, motorcycle: 270 } },
  "Ogden, UT": { copart: { car: 575, motorcycle: 550 } },
  "Oklahoma City, OK": { copart: { car: 400, motorcycle: 345 }, iaai: { car: 400, motorcycle: 320 } },
  "Omaha, NE": { iaai: { car: 430, motorcycle: 300 } },
  "Orlando North, FL": { copart: { car: 420, motorcycle: 350 }, iaai: { car: 420, motorcycle: 350 } },
  "Orlando South, FL": { copart: { car: 420, motorcycle: 350 } },
  "Orlando, FL": { copart: { car: 420, motorcycle: 350 }, iaai: { car: 325, motorcycle: 300 } },
  "Pasco, WA": { copart: { car: 350, motorcycle: 250 } },
  "Pensacola, FL": { iaai: { car: 400, motorcycle: 350 } },
  "Peoria, IL": { copart: { car: 350, motorcycle: 300 } },
  "Permian Basin, TX": { iaai: { car: 450, motorcycle: 350 } },
  "Perris 2, CA": { iaai: { car: 240, motorcycle: 230 } },
  "Perris, CA": { iaai: { car: 240, motorcycle: 230 } },
  "Philadelphia East, PA": { copart: { car: 250, motorcycle: 225 }, iaai: { car: 250, motorcycle: 175 } },
  "Philadelphia, PA": { copart: { car: 250, motorcycle: 225 }, iaai: { car: 250, motorcycle: 175 } },
  "Phoenix, AZ": { copart: { car: 320, motorcycle: 270 }, iaai: { car: 350, motorcycle: 300 } },
  "Pittsburgh East, PA": { copart: { car: 450, motorcycle: 420 }, iaai: { car: 450, motorcycle: 325 } },
  "Pittsburgh North, PA": { copart: { car: 450, motorcycle: 420 }, iaai: { car: 450, motorcycle: 325 } },
  "Pittsburgh South, PA": { copart: { car: 450, motorcycle: 420 } },
  "Pittsburgh West, PA": { copart: { car: 450, motorcycle: 420 } },
  "Port Murray, NJ": { iaai: { car: 225, motorcycle: 200 } },
  "Portage, WI": { iaai: { car: 300, motorcycle: 250 } },
  "Portland (Gorham), ME": { iaai: { car: 575, motorcycle: 350 } },
  "Portland North, OR": { copart: { car: 250, motorcycle: 200 }, iaai: { car: 260, motorcycle: 150 } },
  "Portland South, OR": { copart: { car: 275, motorcycle: 225 }, iaai: { car: 250, motorcycle: 200 } },
  "Portland West, OR": { iaai: { car: 250, motorcycle: 150 } },
  "Providence, RI": { iaai: { car: 350, motorcycle: 350 } },
  "Pulaski, VA": { iaai: { car: 500, motorcycle: 400 } },
  "Punta Gorda South, FL": { copart: { car: 400, motorcycle: 320 } },
  "Punta Gorda, FL": { copart: { car: 400, motorcycle: 320 } },
  "Raleigh, NC": { copart: { car: 320, motorcycle: 300 }, iaai: { car: 320, motorcycle: 280 } },
  "Rancho Cucamonga, CA": { copart: { car: 250, motorcycle: 170 } },
  "Redding, CA": { copart: { car: 170, motorcycle: 625 } },
  "Reno, NV": { copart: { car: 490, motorcycle: 440 }, iaai: { car: 525, motorcycle: 480 } },
  "Richmond East, VA": { copart: { car: 390, motorcycle: 280 } },
  "Richmond, VA": { copart: { car: 400, motorcycle: 300 }, iaai: { car: 320, motorcycle: 270 } },
  "Roanoke, VA": { iaai: { car: 400, motorcycle: 340 } },
  "Rochester, NY": { copart: { car: 400, motorcycle: 350 }, iaai: { car: 400, motorcycle: 350 } },
  "Rosedale, MD": { iaai: { car: 350, motorcycle: 325 } },
  "Sacramento, CA": { copart: { car: 425, motorcycle: 350 }, iaai: { car: 425, motorcycle: 350 } },
  "Saint Cloud, MN": { copart: { car: 400, motorcycle: 400 } },
  "Saint Louis, MO": { copart: { car: 425, motorcycle: 400 }, iaai: { car: 400, motorcycle: 375 } },
  "Salt Lake City North, UT": { copart: { car: 550, motorcycle: 520 } },
  "Salt Lake City, UT": { copart: { car: 550, motorcycle: 520 }, iaai: { car: 500, motorcycle: 450 } },
  "San Antonio South, TX": { iaai: { car: 350, motorcycle: 300 } },
  "San Antonio, TX": { copart: { car: 300, motorcycle: 250 }, iaai: { car: 350, motorcycle: 300 } },
  "San Bernardino, CA": { copart: { car: 200, motorcycle: 200 }, iaai: { car: 250, motorcycle: 250 } },
  "San Diego, CA": { copart: { car: 250, motorcycle: 220 }, iaai: { car: 250, motorcycle: 220 } },
  "San Jose, CA": { copart: { car: 375, motorcycle: 350 } },
  "San Martin, CA": { copart: { car: 500, motorcycle: 450 } },
  "Savannah, GA": { copart: { car: 120, motorcycle: 120 }, iaai: { car: 120, motorcycle: 100 } },
  "Sayreville, NJ": { iaai: { car: 175, motorcycle: 175 } },
  "Scranton, PA": { copart: { car: 350, motorcycle: 320 }, iaai: { car: 325, motorcycle: 275 } },
  "Seaford, DE": { copart: { car: 330, motorcycle: 270 } },
  "Seattle, WA": { iaai: { car: 150, motorcycle: 130 } },
  "Shady Spring, WV": { iaai: { car: 550, motorcycle: 500 } },
  "Shreveport, LA": { copart: { car: 350, motorcycle: 245 }, iaai: { car: 300, motorcycle: 200 } },
  "Sikeston, MO": { copart: { car: 420, motorcycle: 345 } },
  "Sioux Falls, SD": { iaai: { car: 650, motorcycle: 550 } },
  "Somerville, NJ": { copart: { car: 250, motorcycle: 200 } },
  "South Bend, IN": { iaai: { car: 250, motorcycle: 200 } },
  "South Sacramento, CA": { copart: { car: 400, motorcycle: 350 } },
  "Southern Illinois, IL": { copart: { car: 350, motorcycle: 350 } },
  "Southern New Jersey, NJ": { iaai: { car: 200, motorcycle: 165 } },
  "Spartanburg, SC": { copart: { car: 300, motorcycle: 250 } },
  "Spokane, WA": { copart: { car: 350, motorcycle: 300 }, iaai: { car: 350, motorcycle: 300 } },
  "Springfield, MO": { copart: { car: 400, motorcycle: 300 }, iaai: { car: 450, motorcycle: 400 } },
  "Suffolk, VA": { iaai: { car: 400, motorcycle: 330 } },
  "Sun Valley, CA": { copart: { car: 200, motorcycle: 175 } },
  "Syracuse, NY": { copart: { car: 400, motorcycle: 400 }, iaai: { car: 375, motorcycle: 330 } },
  "Tallahassee, FL": { copart: { car: 350, motorcycle: 300 } },
  "Tampa North, FL": { iaai: { car: 350, motorcycle: 325 } },
  "Tampa South, FL": { copart: { car: 300, motorcycle: 300 } },
  "Tampa, FL": { copart: { car: 300, motorcycle: 350 }, iaai: { car: 325, motorcycle: 300 } },
  "Tanner, AL": { copart: { car: 390, motorcycle: 370 } },
  "Taunton, MA": { iaai: { car: 425, motorcycle: 325 } },
  "Templeton, MA": { iaai: { car: 375, motorcycle: 250 } },
  "Tidewater, VA": { iaai: { car: 420, motorcycle: 340 } },
  "Tifton, GA": { copart: { car: 250, motorcycle: 220 }, iaai: { car: 275, motorcycle: 200 } },
  "Trenton, NJ": { copart: { car: 275, motorcycle: 250 } },
  "Tucson, AZ": { copart: { car: 350, motorcycle: 320 }, iaai: { car: 400, motorcycle: 350 } },
  "Tulsa, OK": { copart: { car: 450, motorcycle: 420 }, iaai: { car: 450, motorcycle: 350 } },
  "Vallejo, CA": { copart: { car: 400, motorcycle: 320 } },
  "Van Nuys, CA": { copart: { car: 220, motorcycle: 150 } },
  "Waco, TX": { copart: { car: 320, motorcycle: 320 } },
  "Walton, KY": { copart: { car: 450, motorcycle: 400 } },
  "Washington, DC": { copart: { car: 300, motorcycle: 300 } },
  "Wayland, MI": { copart: { car: 350, motorcycle: 325 } },
  "Webster, NH": { copart: { car: 450, motorcycle: 450 } },
  "West Palm Beach, FL": { copart: { car: 350, motorcycle: 320 }, iaai: { car: 350, motorcycle: 325 } },
  "West Warren, MA": { copart: { car: 375, motorcycle: 295 } },
  "Wheeling, IL": { copart: { car: 150, motorcycle: 150 } },
  "Wichita, KS": { copart: { car: 700, motorcycle: 650 }, iaai: { car: 700, motorcycle: 600 } },
  "Wilmington, NC": { iaai: { car: 350, motorcycle: 300 } },
  "York Haven, PA": { copart: { car: 300, motorcycle: 275 } },
  "York Springs, PA": { iaai: { car: 275, motorcycle: 225 } },
};

export const SUV_SURCHARGE_USD = 50;

/**
 * Real local-transportation rate for a pickup location, given which auction
 * network it's being picked up from. Falls back to the other network's rate
 * for that same city when the selected network has none listed (some cities
 * only exist in one network's sheet), then to `fallbackUsd` if neither does.
 * SUV reuses the Car rate plus `SUV_SURCHARGE_USD`.
 */
export function localTransportRateUsd(
  location: string,
  network: AuctionNetwork,
  vehicleKind: "car" | "suv" | "motorcycle",
  fallbackUsd: number
): number {
  const byNetwork = LOCAL_TRANSPORT_RATES[location];
  if (!byNetwork) return fallbackUsd;

  const rateVehicle = vehicleKind === "suv" ? "car" : vehicleKind;
  const otherNetwork: AuctionNetwork = network === "copart" ? "iaai" : "copart";
  const base = byNetwork[network]?.[rateVehicle] ?? byNetwork[otherNetwork]?.[rateVehicle];

  if (base == null) return fallbackUsd;
  return vehicleKind === "suv" ? base + SUV_SURCHARGE_USD : base;
}
