/**
 * Copart + IAAI pickup/branch locations, merged and deduplicated, compiled
 * from published branch-location listings (not a live feed). Branches open,
 * close, and get renamed over time, so treat this as a strong representative
 * list covering all 50 states rather than a guaranteed-current inventory —
 * verify an exact branch with us before relying on it for logistics.
 */
export const PICKUP_LOCATIONS: string[] = [
  "Tanner, AL",
  "Birmingham, AL",
  "Montgomery, AL",
  "Mobile, AL",
  "Dothan, AL",
  "Huntsville, AL",
  "Mobile South, AL",
  "Anchorage, AK",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Little Rock, AR",
  "Fayetteville, AR",
  "Vallejo, CA",
  "Sacramento, CA",
  "South Sacramento, CA",
  "Hayward, CA",
  "Fresno, CA",
  "Bakersfield, CA",
  "San Jose, CA",
  "San Bernardino, CA",
  "Los Angeles, CA",
  "Van Nuys, CA",
  "San Diego, CA",
  "Martinez, CA",
  "Rancho Cucamonga, CA",
  "Sun Valley, CA",
  "Anaheim, CA",
  "Carson, CA",
  "Perris, CA",
  "East Bay, CA",
  "Adelanto, CA",
  "Antelope, CA",
  "Colton, CA",
  "CrashedToys Sacramento, CA",
  "Fontana, CA",
  "Fremont, CA",
  "High Desert, CA",
  "Long Beach, CA",
  "Los Angeles South, CA",
  "Mentone, CA",
  "Napa, CA",
  "North Hollywood, CA",
  "Perris 2, CA",
  "Redding, CA",
  "San Martin, CA",
  "Denver, CO",
  "Denver South, CO",
  "Denver East, CO",
  "Colorado Springs, CO",
  "Denver Central, CO",
  "Hartford, CT",
  "Hartford South, CT",
  "Hartford Springfield, CT",
  "Seaford, DE",
  "New Castle, DE",
  "Washington, DC",
  "Miami North, FL",
  "Miami Central, FL",
  "Miami South, FL",
  "Tampa South, FL",
  "Jacksonville West, FL",
  "Jacksonville East, FL",
  "Orlando, FL",
  "Orlando North, FL",
  "West Palm Beach, FL",
  "Fort Pierce, FL",
  "Ocala, FL",
  "Tallahassee, FL",
  "Punta Gorda, FL",
  "Clearwater, FL",
  "Fort Myers, FL",
  "Jacksonville North, FL",
  "Jacksonville, FL",
  "Miami, FL",
  "Orlando South, FL",
  "Pensacola, FL",
  "Punta Gorda South, FL",
  "Tampa North, FL",
  "Tampa, FL",
  "Atlanta, GA",
  "Atlanta West, GA",
  "Atlanta East, GA",
  "Atlanta South, GA",
  "Atlanta North, GA",
  "Savannah, GA",
  "Tifton, GA",
  "Cartersville, GA",
  "Augusta, GA",
  "Macon, GA",
  "Honolulu, HI",
  "Boise, ID",
  "Chicago North, IL",
  "Chicago South, IL",
  "Chicago West, IL",
  "Peoria, IL",
  "Wheeling, IL",
  "Bartlett, IL",
  "Lincoln, IL",
  "Southern Illinois, IL",
  "Indianapolis, IN",
  "Fort Wayne, IN",
  "Hammond, IN",
  "Dyer, IN",
  "Hartford City, IN",
  "Indianapolis South, IN",
  "South Bend, IN",
  "Des Moines, IA",
  "Davenport, IA",
  "CrashedToys Eldridge, IA",
  "Kansas City, KS",
  "Wichita, KS",
  "Lexington West, KY",
  "Lexington East, KY",
  "Walton, KY",
  "Louisville, KY",
  "Ashland, KY",
  "Bowling Green, KY",
  "Earlington, KY",
  "Louisville North, KY",
  "Baton Rouge, LA",
  "New Orleans, LA",
  "Shreveport, LA",
  "Lafayette, LA",
  "New Orleans East, LA",
  "Lyman, ME",
  "Portland (Gorham), ME",
  "Baltimore, MD",
  "Dundalk, MD",
  "Elkton, MD",
  "Baltimore East, MD",
  "Laurel, MD",
  "Metro DC, MD",
  "Rosedale, MD",
  "Boston South, MA",
  "Boston North, MA",
  "West Warren, MA",
  "Boston (Shirley), MA",
  "Freetown, MA",
  "Taunton, MA",
  "Templeton, MA",
  "Detroit, MI",
  "Lansing, MI",
  "Kincheloe, MI",
  "Flint, MI",
  "Ionia, MI",
  "Grand Rapids, MI",
  "Wayland, MI",
  "Minneapolis, MN",
  "Minneapolis North, MN",
  "Saint Cloud, MN",
  "CrashedToys East Bethel, MN",
  "CrashedToys Minneapolis, MN",
  "Minneapolis South, MN",
  "Minneapolis/St. Paul, MN",
  "Jackson, MS",
  "Grenada, MS",
  "Gulf Coast, MS",
  "Saint Louis, MO",
  "Springfield, MO",
  "Columbia, MO",
  "Sikeston, MO",
  "Kansas City East, MO",
  "Helena, MT",
  "Billings, MT",
  "Missoula, MT",
  "Lincoln, NE",
  "Omaha, NE",
  "Las Vegas, NV",
  "Reno, NV",
  "Candia, NH",
  "Manchester, NH",
  "Webster, NH",
  "Glassboro, NJ",
  "Somerville, NJ",
  "Trenton, NJ",
  "Avenel, NJ",
  "Central New Jersey, NJ",
  "Englishtown, NJ",
  "Glassboro East, NJ",
  "Glassboro West, NJ",
  "Northern New Jersey, NJ",
  "Port Murray, NJ",
  "Sayreville, NJ",
  "Southern New Jersey, NJ",
  "Albuquerque, NM",
  "Newburgh, NY",
  "Syracuse, NY",
  "Long Island, NY",
  "Rochester, NY",
  "Albany, NY",
  "Buffalo, NY",
  "China Grove, NC",
  "Raleigh, NC",
  "Mebane, NC",
  "Asheville, NC",
  "Charlotte, NC",
  "Concord, NC",
  "Greensboro, NC",
  "Mocksville, NC",
  "Wilmington, NC",
  "Columbus, OH",
  "Cleveland East, OH",
  "Cleveland West, OH",
  "Dayton, OH",
  "Akron-Canton, OH",
  "Cincinnati, OH",
  "Cincinnati South, OH",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Portland North, OR",
  "Portland South, OR",
  "Eugene, OR",
  "Portland West, OR",
  "Philadelphia, PA",
  "Philadelphia East, PA",
  "Pittsburgh North, PA",
  "Pittsburgh South, PA",
  "Pittsburgh East, PA",
  "Harrisburg, PA",
  "York Haven, PA",
  "Chambersburg, PA",
  "Altoona, PA",
  "Scranton, PA",
  "Bridgeport, PA",
  "Erie, PA",
  "Pittsburgh West, PA",
  "York Springs, PA",
  "Columbia, SC",
  "Greer, SC",
  "Charleston, SC",
  "Greenville, SC",
  "Lexington, SC",
  "North Charleston, SC",
  "Spartanburg, SC",
  "Memphis, TN",
  "Nashville, TN",
  "Knoxville, TN",
  "Chattanooga, TN",
  "Houston, TX",
  "Dallas, TX",
  "Dallas South, TX",
  "Dallas/Fort Worth, TX",
  "Fort Worth, TX",
  "Lufkin, TX",
  "Longview, TX",
  "El Paso, TX",
  "Austin, TX",
  "Austin North, TX",
  "McAllen, TX",
  "Abilene, TX",
  "San Antonio, TX",
  "Amarillo, TX",
  "Corpus Christi, TX",
  "Waco, TX",
  "Andrews, TX",
  "Fort Worth North, TX",
  "Houston East, TX",
  "Houston North, TX",
  "Houston South, TX",
  "IAA CAT Houston, TX",
  "Lubbock, TX",
  "Permian Basin, TX",
  "San Antonio South, TX",
  "Salt Lake City, UT",
  "Ogden, UT",
  "Salt Lake City North, UT",
  "Burlington, VT",
  "Danville, VA",
  "Hampton, VA",
  "Richmond, VA",
  "Culpeper, VA",
  "Fredericksburg South, VA",
  "Fredericksburg, VA",
  "Northern Virginia, VA",
  "Pulaski, VA",
  "Richmond East, VA",
  "Roanoke, VA",
  "Suffolk, VA",
  "Tidewater, VA",
  "North Seattle, WA",
  "Graham, WA",
  "Pasco, WA",
  "Spokane, WA",
  "Seattle, WA",
  "Charleston, WV",
  "Buckhannon, WV",
  "Shady Spring, WV",
  "Madison, WI",
  "Milwaukee, WI",
  "Appleton, WI",
  "Madison South, WI",
  "Milwaukee North, WI",
  "Milwaukee South, WI",
  "Portage, WI",
  "Casper, WY",
  "Bismarck, ND",
  "Fargo, ND",
  "Exeter, RI",
  "Providence, RI",
  "Sioux Falls, SD",
];
